version: '2'
services:
  bot:
    build:
      context: .
    command: python tjbot/bot.py
    restart: on-failure
    depends_on:
      - db
    environment:
      - TJBOT_DB_HOST=db
      - TJBOT_API_KEY
      - TJBOT_AUTO_QUESTION_TIME
    env_file:
      - .env
  db:
    image: mongo:3.0.14
    command: mongod --smallfiles
    restart: on-failure
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata:
